### PR TITLE
Fix crash in FPicker on Android OS >= 7.0

### PR DESCRIPTION
**Pull request by EXL**
When I try to enter to the root directory "/" I get app crash on Android OS >= 7.0

to_gh_a

```
D/OpenGLRenderer: endAllActiveAnimators on 0x9d90fb00 (RippleDrawable) with handle 0xab3c95f0
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #5
	Process: in.celest.xash3d.hl, PID: 2453
	java.lang.RuntimeException: An error occurred while executing doInBackground()
		at android.os.AsyncTask$3.done(AsyncTask.java:325)
		at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
		at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
		at java.util.concurrent.FutureTask.run(FutureTask.java:242)
		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
		at java.lang.Thread.run(Thread.java:761)
	Caused by: java.lang.NullPointerException
		at java.io.File.<init>(File.java:262)
		at in.celest.xash3d.FPicker$Fill.doInBackground(FPicker.java:84)
		at in.celest.xash3d.FPicker$Fill.doInBackground(FPicker.java:68)
		at android.os.AsyncTask$2.call(AsyncTask.java:305)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
		at java.lang.Thread.run(Thread.java:761)
D/OpenGLRenderer: endAllActiveAnimators on 0x9ccb3200 (ListView) with handle 0x9c5f3390
```
When directory list **dirs** is null and **folder** variable is root "/" the `folder = new File(folder.getParent())` expression throws the `NullPointerException` exception.

In addition, the code which was supposed to return **dir** list never worked:

screenshot_20170623_094628

### CODE REVIEW

**Comment by mittorn** [comment]
Is not it better to check folder before folder.getParent()?
It cannot be null after folder.getParent() because check become unreachable after exception, but can be before.

**Comment by mittorn** [comment]
Also i think, catching NullPointerException is bad because referencing null objects is bad, it is better not to do bad things prior to catching it.

**Comment by EXL** [comment]
@mittorn in this context **folder** [can't be null](https://github.com/FWGS/xash3d-android-project/blob/426b088e16ace03e3de108f48d285686e9d100c1/src/in/celest/xash3d/FPicker.java#L79), but `folder.getParent()` can. The crash was because the parent of root ("/") is null.

> catching NullPointerException is bad

Yes, you are right. I think it will be better:

```java
while( dirs == null )
{
	String parent = folder.getParent();
	if (parent != null)
		folder = new File(parent);
	else
		folder = new File(Environment.getExternalStorageDirectory().toString());
	dirs = folder.listFiles();
}
```
I will open a new PR. Are there any suggestions yet?

**Comment by mittorn** [comment]
Yes, all seems to be OK now

**Pull request merged**
