### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by FWGS-weblate**
Translations update from [Weblate](https://l10n.mentality.rip/projects/xash3d-fwgs-android/android-translations/) for Xash3D FWGS/Android translations.

### CODE REVIEW

**Comment by davidmacalister** [comment]
doesn't work anymore

**Comment by a1batross** [comment]
Yeah, weblate is pretty annoying to maintain.

**Comment by davidmacalister** [comment]
I want to translate Xash3D's Halif Life interface into Brazilian Portuguese, how could I collaborate?

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-android-project/blob/gradle/app/src/main/res/values/strings.xml

https://github.com/FWGS/xash3d-android-project/blob/gradle/app/src/main/res/values-pt-rBR/strings.xml

You need to take string values from first file and copy them to the second and translate.

**Comment by davidmacalister** [comment]
> https://github.com/FWGS/xash3d-android-project/blob/gradle/app/src/main/res/values/strings.xml
> 
> https://github.com/FWGS/xash3d-android-project/blob/gradle/app/src/main/res/values-pt-rBR/strings.xml
> 
> You need to take string values from first file and copy them to the second and translate.

Ok I will do that, then what do I do with the file?

**Comment by a1batross** [comment]
There should be an edit button, GitHub will ask you to _fork_ the repository, do that and then GitHub should ask you about making a _pull request_. 

After that we will review and accept your changes.

**Comment by davidmacalister** [comment]
> There should be an edit button, GitHub will ask you to _fork_ the repository, do that and then GitHub should ask you about making a _pull request_.
> 
> After that we will review and accept your changes.

Here it is https://github.com/FWGS/xash3d-android-project/pull/209

**Comment by davidmacalister** [comment]
I also want to translate the interface of games, like half life 1, there is already a translation of the interface made for the PC version on Steam, how can I translate the compatible menu with Xash3D and adapt it with Xash3D 

Original
Screenshot_20240716-201751

Translated (Original version, not Xash3D)
Screenshot_20240716-202614

@a1batross

**Pull request merged**
